runtime: nodejs16
instance_class: F2
service : api
automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto

env_variables:
  MONGODB_URI: "mongodb+srv://kannanopenwave:mongo-v1@mern-v1.iiobbps.mongodb.net"
